### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by jonaskello** [LasLabs/docker-alpine-samba-dc#5]
Would be nice to have docker version tags instead of just `latest`.

If I create a container now, and then re-create it in a few months I may get a different version without even knowing it as all there is now is `latest`. If I create a container with a version tag such as `1.0.0` and then re-create with the same tag at any point in the future I am guaranteed to have the re-creation work exactly as before.

**Comment by lasley** [comment]
Good call @jonaskello. Dockerhub updated, #6 created for the docs, which will be tagged as `0.1.0` after merge
